"""Regenerate the audit-summary strings in the two evidence matrices from their rows.

Written after independent review finding F4: the prose `summary` in parity-matrix.json
still carried the pre-verification merge tally while the machine `status_tally` and
section B carried the corrected one. The numbers below are computed, never typed.
"""
import json, collections

PM='/home/user/tnr-tools/docs/forge_next/evidence/parity-matrix.json'
AF='/home/user/tnr-tools/docs/forge_next/evidence/admin-feasibility.json'

METHOD = ("one adversarial verifier per DECISIVE row (forge-next-deep-dive workflow, Verify phase): every GAP, every "
          "INTENTIONAL DIFFERENCE, every retirement blocker and every low- or medium-confidence row. Rows outside that "
          "set carry 'not verified' and are the merge agent's finding, not an audited one. CORRECTED rows were replaced "
          "by the verifier's full corrected row with the original kept under verification.original_row; REFUTED rows "
          "were kept with the verdict and reasoning for the reader. Gate rows are not verified by construction.")

d=json.load(open(PM))
rows=d['rows']
cap=[r for r in rows if r.get('kind')=='capability']
gates=[r for r in rows if r.get('kind')=='gate']
st=collections.Counter(r['parity_status'] for r in cap)
bl=collections.Counter()
for r in cap:
    b=str(r.get('retirement_blocker','')).strip().lower()
    bl['yes' if b.startswith('yes') else 'conditional' if b.startswith('conditional') else 'no' if b.startswith('no') else 'split'] += 1
yes=[r for r in cap if str(r.get('retirement_blocker','')).strip().lower().startswith('yes')]
intl=[r for r in cap if r['parity_status']=='INTENTIONAL DIFFERENCE']
ver=collections.Counter(str(r.get('verification',{}).get('verdict','not verified')) for r in cap)

def short(r):
    text = r['capability'].split('(')[0].split('. ')[0]
    head = text.split(':')[0].strip()
    if len(head) >= 12:
        text = head
    text = text.strip().rstrip('.,;').strip()
    return f"{r['id']} {text}"

d['summary'] = (
 f"Builder -> Forge parity matrix: {len(cap)} capability rows and {len(gates)} retirement gates merged from the builder, "
 "forge and harvest-evidence inventories, with every disputed or missing cell re-read in builder_bundle.js (all 892 lines, "
 "line-verified), forge/src/** and the 345d18ac game checkout, then verified row by row across the decisive set. "
 "TALLY, recomputed from the rows after verification and identical to B_PARITY_MATRIX.md: "
 + ", ".join(f"{k} {st[k]}" for k in ('FORGE BETTER','PARITY','INTENTIONAL DIFFERENCE','GAP'))
 + "; retirement_blocker " + ", ".join(f"{k} {bl[k]}" for k in ('yes','conditional','no','split') if bl[k])
 + f". VERIFICATION over the {len(cap)} capability rows: " + ", ".join(f"{k} {v}" for k,v in sorted(ver.items()))
 + f" (the {len(gates)} gate rows are unverified by construction, so the whole-file count of "
   f"{sum(v for k,v in ver.items() if k != 'CORRECTED') + len(gates)} 'not verified' includes them). "
 + f"HARD BLOCKERS ({bl['yes']}): " + "; ".join(short(r) for r in yes) + ". "
 + f"INTENTIONAL DIFFERENCES ({st['INTENTIONAL DIFFERENCE']}), each backed by a committed doc: "
 + "; ".join(short(r) for r in intl) + ". "
 + "Conditional blockers are the nine rows whose retirement_blocker begins 'conditional', and P-34 is the one split row "
   "(law 77/78 semantics no, the runtime-only tag set conditional). "
   "HEADLINE EVIDENCE: no Forge write has ever run live (all 7 Forge bundles have entries 0), so every FORGE BETTER "
   "write-path row is fixture-proven only and gate G-08 (live write proof) is mandatory. "
   "DOCUMENTATION DEFECTS FOUND: lints.mjs:15-16 and BUILDER_APP_NOTES.md:703 cite a docs/RULINGS.md 'law 19 contradicted' "
   "entry that does not exist; BUILDER_APP_NOTES.md:866-868/801-811 are stale versus code; pipeline.md:253-255 describes a "
   "limiter model the pinned source contradicts. "
   "This string is generated by evidence/gen_evidence_summary.py from the rows; do not hand-edit it."
)
d['verification']['method']=METHOD
d['tally_note']=("Recomputed from the rows after adversarial verification; the earlier header was the pre-verification merge. "
                 "The prose summary above is regenerated from the same rows by evidence/gen_evidence_summary.py, so it "
                 "cannot drift from status_tally again.")
json.dump(d, open(PM,'w'), indent=1)
print('parity-matrix.json summary regenerated')

a=json.load(open(AF))
arows=a['rows']
av=collections.Counter(str(r.get('verification',{}).get('verdict','not verified')) for r in arows)
a['verification']['method']=METHOD
a['verification']['scope_note']=(f"{len(arows)} rows in this file; verification verdicts: "
    + ", ".join(f"{k} {v}" for k,v in sorted(av.items()))
    + ". The decisive set here is every content-class row and every cross-cutting row that a phase-4 design would rest on.")
json.dump(a, open(AF,'w'), indent=1)
print('admin-feasibility.json method corrected')
