// Derive the human-readable research-read registry descriptor from the registry module itself.
//
// This exists so a reviewer can read the admission decisions as a table without reading the module,
// and so that table can never drift from what the code actually does: it is GENERATED, and
// test/research.registry.test.mjs fails when the committed file and the derivation disagree. The
// module is the authority; this file is a projection of it and must never be hand-edited.
//
// Run: node tools/derive_registry.mjs      (writes ../forge/RESEARCH_REGISTRY.md)

import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { RESEARCH_READS, RESEARCH_PATHS, REGISTRY_PIN, MAX_PAGES, readMode } from "../src/research/registry.mjs";
import { PROCEDURES } from "../src/transport/procedures.mjs";

const OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "RESEARCH_REGISTRY.md");

const inputCell = (row) => {
  if (!row.input) return "_(none)_";
  const req = Object.keys(row.input.required).map((k) => `\`${k}\``);
  const opt = Object.keys(row.input.optional).map((k) => `\`${k}?\``);
  return [...req, ...opt].join(" ");
};
const pageCell = (row) => (row.page ? `${row.page.mode}, default limit ${row.page.defaultLimit}, max ${row.page.maxLimit}` : "—");

export function render() {
  const rows = RESEARCH_PATHS.map((path) => {
    const row = RESEARCH_READS[path];
    const p = PROCEDURES[path];
    return `| \`${path}\` | ${p.kind} | ${p.auth} | ${p.limited ? "yes" : "no"} | ${readMode(path)} | ${inputCell(row)} | ${pageCell(row)} | \`${row.tier}\` | ${row.demand} | ${row.source} |`;
  });
  return `<!-- GENERATED by forge/tools/derive_registry.mjs from forge/src/research/registry.mjs. Do not edit by hand. -->
# Forge research-read registry

Every read Forge will issue as a research capture, and nothing else. A path without a row here is
refused before transport, whatever the game would answer (\`RUL-2026-09-17-002\`).

- **Source pin audited:** \`${REGISTRY_PIN}\` (\`studie-tech/TheNinjaRPG\`), the same pin
  \`forge/src/runner/fields.json\` and \`nested.json\` carry; \`tools/check_boundaries.mjs\` holds the three equal.
- **Tier** is both the default and the ceiling. A manifest may ask for that tier or any narrower one
  (\`local-only\` < \`projected\` < \`repo-safe\`); widening one is a reviewed edit of the registry module,
  never a manifest key (\`RUL-2026-09-17-001\`).
- **Kind, auth and limiter** are not restated here. They are read from
  \`forge/src/transport/procedures.mjs\`, which owns the source facts; this table only shows them.
- **Paged** reads are bounded twice: by the row's own audited maximum limit, and by the
  \`MAX_PAGES\` = ${MAX_PAGES} ceiling no manifest can exceed.

| path | kind | auth | limited | read mode | input contract | paging | tier | demanded by | audited at |
|---|---|---|---|---|---|---|---|---|---|
${rows.join("\n")}

## Adding a row

1. a committed, reviewed manifest or work package must actually need the procedure;
2. audit its contract at the declared pin — kind, auth, limiter, exact input, pagination — and record
   the file and line;
3. add the row at tier \`local-only\` unless it is a content-record point read already approved for
   repository persistence;
4. add the evidence to \`forge/test/research.registry.test.mjs\`;
5. regenerate this file with \`node tools/derive_registry.mjs\`.
`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  writeFileSync(OUT, render());
  console.log("wrote " + OUT);
}
