#!/usr/bin/env python3
"""Generate docs/design/bloodright/CLASSIFICATION_DEPENDENCIES.md: per-bloodline
classification label, kind, census collisions, injected children, item gates and
adverse rows, from the kit dossiers. Referenced by ENGINE_GAP_REGISTER.md.

  python3 scripts/bloodright/classification_table.py [--check]
"""
from __future__ import annotations

import argparse
import glob
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import bloodright_lib as L  # noqa: E402

OUT = os.path.join(L.DESIGN_DIR, "CLASSIFICATION_DEPENDENCIES.md")
KITS = os.path.join(L.DESIGN_DIR, "kits")


def build() -> str:
    rows = []
    for p in sorted(glob.glob(os.path.join(KITS, "*.json"))):
        d = L.load_json(p)
        c = d["classification_audit"]
        coll = {}
        for x in c["census_collisions_on_signature_elements"]:
            coll.setdefault(x["element"], []).append(f"{x['name'].strip()} [{x['disposition']}]")
        colltxt = "; ".join(f"{el}: {', '.join(v)}" for el, v in coll.items()) or "none"
        inj = ", ".join(f"{ic['child_name']} (`{ic['child_bloodline_id'] or 'no bloodlineId'}`)" for ic in c["injected_children"]) or "none"
        gated = ", ".join(c["item_gated_jutsu"]) or "none"
        adverse = ", ".join(f"{a['jutsu']}#{a['row']} {a['tag']}" for a in d["adverse_supported_rows"]) or "none"
        rows.append((d["review_id"], d["name"].strip(), d["rank"], d["disposition"], c["proposed_label"], c["label_kind"],
                     "yes" if c.get("element_exclusive_within_census") else "no", colltxt, inj, gated, adverse,
                     ", ".join(c["mode_restricted_jutsu"]) or "none"))
    out = ["# Bloodright classification dependencies\n",
           "Generated by `scripts/bloodright/classification_table.py` from the kit dossiers. `Label kind` **element** means one non-basic element appears on every damage/pierce row and could serve as the classification key if the resolver scoped it to the bloodline; **bloodline-keyed extension** means no existing element isolates the kit (none, a basic element, or several elements), so a bloodline-keyed label is required. `Exclusive in census` is true only when no other captured bloodline carries the element on any row; it says nothing about ordinary jutsu (unverified).\n",
           "| Review | Bloodline | Rank | Decision | Label | Kind | Exclusive in census | Census collisions on signature elements | Injected children | Item-gated jutsu | Adverse supported rows | Mode-restricted |",
           "|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for r in sorted(rows):
        out.append("| " + " | ".join(r) + " |")
    kinds = {}
    for r in rows:
        kinds[r[5]] = kinds.get(r[5], 0) + 1
    out.append("\nCounts: " + "; ".join(f"{k}: {v}" for k, v in sorted(kinds.items())) + f"; exclusive in census: {sum(1 for r in rows if r[6]=='yes')} of {len(rows)}.\n")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    txt = build()
    if args.check:
        cur = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else None
        if cur != txt:
            print(f"STALE {OUT}")
            return 2
        print("classification table current")
        return 0
    L.write_text(OUT, txt)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
