#!/usr/bin/env python3
"""Generate docs/design/bloodright/CLASSIFICATION_DEPENDENCIES.md: per-bloodline
element-wide potency classification (RUL-2026-10-03-005), its status, kit jutsu that
need an authored jutsu classification, bloodlines sharing the element (expected),
injected children, item gates (castability only) and adverse rows, from the kit
dossiers. Referenced by ENGINE_GAP_REGISTER.md.

  python3 scripts/bloodright/classification_table.py [--check]
"""
from __future__ import annotations

import argparse
import glob
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import bloodright_lib as L  # noqa: E402

OUT = os.path.join(L.DESIGN_DIR, "CLASSIFICATION_DEPENDENCIES.md")
KITS = os.path.join(L.DESIGN_DIR, "kits")


def build() -> str:
    rows = []
    for p in sorted(glob.glob(os.path.join(KITS, "*.json"))):
        d = L.load_json(p)
        c = d["classification_audit"]
        shared = {}
        for x in c["shared_element_bloodlines"]:
            shared.setdefault(x["element"], []).append(x["name"].strip())
        sharedtxt = "; ".join(f"{el}: {len(v)}" for el, v in shared.items()) or "none"
        authored = ", ".join(c["kit_jutsu_by_authored_classification"]) or "none"
        inj = ", ".join(f"{ic['child_name']} (`{ic['child_bloodline_id'] or 'no bloodlineId'}`)" for ic in c["injected_children"]) or "none"
        gated = ", ".join(c["item_gated_jutsu"]) or "none"
        adverse = ", ".join(f"{a['jutsu']}#{a['row']} {a['tag']}" for a in d["adverse_supported_rows"]) or "none"
        rows.append((d["review_id"], d["name"].strip(), d["rank"], d["disposition"], c["proposed_label"],
                     ", ".join(c["qualifying_elements"]) or "—", c["classification_status"], authored, sharedtxt, inj, gated, adverse,
                     ", ".join(c["mode_restricted_jutsu"]) or "none"))
    out = ["# Bloodright classification dependencies\n",
           "Generated by `scripts/bloodright/classification_table.py` from the kit dossiers. Potency is **element-wide** (RUL-2026-10-03-005): a Bloodright modifier reaches matching supported tags on every jutsu of the qualifying element, from any source. Bloodline id, equipment, injected-child provenance and jutsu names are not selectors; equipment only gates castability.\n",
           "- **element**: one signature element on the kit's damage/pierce rows; it is the classification.",
           "- **multi-element: director review**: several signature elements; the proposal lists all of them, and choosing one, all, or an extension is a director decision.",
           "- **requires classification extension**: no non-None signature element; a new jutsu classification (placeholder named after the bloodline) would be needed. It is not a bloodline-id selector.\n",
           "`Authored classification` lists kit jutsu whose own rows carry no qualifying element (train.ts `checkJutsuElements` union): they are in scope only if their jutsu records carry the classification as authored data, which needs the proposed jutsu-classification field (ENGINE_GAP_REGISTER G1). `Bloodlines sharing the element` counts other captured bloodlines with jutsu of the element; sharing is expected, and those bloodline jutsu are castable only by their own owners (train.ts 185-188). Off-kit NORMAL/SPECIAL/EVENT/FORBIDDEN coverage is unverified everywhere.\n",
           "| Review | Bloodline | Rank | Decision | Classification | Qualifying elements | Status | Authored classification needed | Bloodlines sharing the element | Injected children | Item-gated jutsu (castability) | Adverse supported rows | Mode-restricted |",
           "|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for r in sorted(rows):
        out.append("| " + " | ".join(r) + " |")
    kinds = {}
    for r in rows:
        kinds[r[6]] = kinds.get(r[6], 0) + 1
    out.append("\nCounts: " + "; ".join(f"{k}: {v}" for k, v in sorted(kinds.items())) +
               f"; kits needing an authored classification for at least one jutsu: {sum(1 for r in rows if r[7] != 'none')} of {len(rows)}.\n")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    txt = build()
    if args.check:
        cur = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else None
        if cur != txt:
            print(f"STALE {OUT}")
            return 2
        print("classification table current")
        return 0
    L.write_text(OUT, txt)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
