#!/usr/bin/env python3
"""Generate docs/design/bloodright/PLANNING_STATUS.md: completed vs blocked
bloodlines, validator state per tree, batches, and totals.

  python3 scripts/bloodright/planning_status.py [--check]

Blockers are read from docs/design/bloodright/blockers.json when present
({"<slug>": "<precise reason>"}); a bloodline with neither a tree nor a
blocker entry is reported as "not begun".
"""
from __future__ import annotations

import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import bloodright_lib as L  # noqa: E402

OUT = os.path.join(L.DESIGN_DIR, "PLANNING_STATUS.md")
TREES = os.path.join(L.DESIGN_DIR, "trees")
BLOCKERS = os.path.join(L.DESIGN_DIR, "blockers.json")
BATCHES = os.path.join(L.DESIGN_DIR, "batches.json")
REVIEW_LOG = os.path.join(L.DESIGN_DIR, "review_log.json")


def build() -> str:
    roster = L.load_roster()
    snapshot = L.load_snapshot()
    idx = L.census_index(snapshot, roster)
    blockers = L.load_json(BLOCKERS) if os.path.exists(BLOCKERS) else {}
    batches = L.load_json(BATCHES) if os.path.exists(BATCHES) else {}
    slug_batch = {s: b for b, lst in batches.items() for s in lst}
    review = L.load_json(REVIEW_LOG) if os.path.exists(REVIEW_LOG) else {}
    rows = []
    totals = {"complete": 0, "complete_with_warnings": 0, "blocked": 0, "not_begun": 0, "invalid": 0}
    for bid in roster["approved_remaining_ids"]:
        rec = idx[bid]["record"]
        name = rec["name"].strip()
        slug = L.slugify(name)
        tpath = os.path.join(TREES, slug + ".json")
        vpath = os.path.join(TREES, slug + ".validation.json")
        if os.path.exists(tpath) and os.path.exists(vpath):
            v = L.load_json(vpath)
            t = L.load_json(tpath)
            errs = v.get("structure_errors", [])
            warns = v.get("warnings", [])
            a = v.get("audit", {})
            if errs:
                state = "INVALID"; totals["invalid"] += 1
            elif warns:
                state = "complete (warnings)"; totals["complete_with_warnings"] += 1
            else:
                state = "complete"; totals["complete"] += 1
            detail = (f"{a.get('available_skills')} nodes ({a.get('foundation_count')}/{a.get('hidden_art_count')}/{a.get('advanced_art_count')}), "
                      f"{len(v.get('examples', []))} builds, {a.get('full_budget_allocations')} legal 4-BP allocations, min two-Advanced {a.get('minimum_two_advanced_cost')}, "
                      f"{t.get('classification', {}).get('potency_classification')} ({t.get('classification', {}).get('classification_status')})")
            if t.get("narrow_kit_exception"):
                detail += "; narrow-kit exception"
            dr = t.get("design_review") or {}
            if dr.get("status"):
                detail += f"; status: {dr['status']}"
            if dr.get("director_review") and dr["director_review"] != "none":
                detail += "; director review recommended"
            rv = review.get(slug)
            if rv:
                detail += f"; review: {rv.get('final_review')}"
                if rv.get("open_major"):
                    detail += " (open: " + " / ".join(rv["open_major"]) + ")"
            if warns:
                detail += "; warnings: " + " / ".join(warns)
            rows.append((rec["review_id"], name, rec["rank"], slug_batch.get(slug, "—"), state, detail, f"[tree]({'trees/' + slug + '.md'}) · [svg]({'trees/' + slug + '.svg'}) · [dossier]({'kits/' + slug + '.md'})"))
        elif slug in blockers:
            totals["blocked"] += 1
            rows.append((rec["review_id"], name, rec["rank"], slug_batch.get(slug, "—"), "BLOCKED", blockers[slug], f"[dossier]({'kits/' + slug + '.md'})"))
        else:
            totals["not_begun"] += 1
            rows.append((rec["review_id"], name, rec["rank"], slug_batch.get(slug, "—"), "not begun", "", f"[dossier]({'kits/' + slug + '.md'})"))
    out = ["# Bloodright planning status\n",
           f"Generated by `scripts/bloodright/planning_status.py`. Approved remaining bloodlines: {len(roster['approved_remaining_ids'])}. "
           f"Complete: {totals['complete'] + totals['complete_with_warnings']} ({totals['complete_with_warnings']} with validator warnings) · Blocked: {totals['blocked']} · Invalid: {totals['invalid']} · Not begun: {totals['not_begun']}. "
           "Taiyo Kami is the separate worked reference (`trees/taiyo_kami.*`, regenerated from the approved values; `examples/` keeps the original handoff). Blood-Enchanted Eyes, Shakunetsu Sakura and Arashima follow RUL-2026-10-04-001..003; every other tree is a Fable proposal; final tuning and acceptance are user decisions.\n",
           "| Review | Bloodline | Rank | Batch | State | Detail | Links |", "|---|---|---|---|---|---|---|"]
    for r in sorted(rows):
        out.append("| " + " | ".join(r) + " |")
    out.append("\nValidation commands: `python3 scripts/bloodright/build_all.py --check` (dossiers, trees, renders, matrix, ledgers) and `python3 -m unittest scripts/bloodright/tests/test_bloodright_tools.py`.\n")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    txt = build()
    if args.check:
        cur = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else None
        if cur != txt:
            print(f"STALE {OUT}")
            return 2
        print("planning status current")
        return 0
    L.write_text(OUT, txt)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
