#!/usr/bin/env python3
"""Generate docs/design/bloodright/ROSTER_LEDGER.md from roster.json and the kit snapshot.

Every census record is listed with its disposition; records or jutsu discovered
during planning that the roster does not classify are appended under
"Discovered during planning" without changing roster.json (membership changes
need a roster amendment).

  python3 scripts/bloodright/roster_ledger.py [--check]
"""
from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import bloodright_lib as L  # noqa: E402

OUT = os.path.join(L.DESIGN_DIR, "ROSTER_LEDGER.md")


def build() -> str:
    roster = L.load_roster()
    snapshot = L.load_snapshot()
    idx = L.census_index(snapshot, roster)
    recs = roster["records"]
    approved = set(roster["approved_remaining_ids"])
    reference = set(roster["reference_ids"])
    counts = roster["decision_counts"]
    out = ["# Bloodright roster and exclusion ledger\n",
           f"Generated by `scripts/bloodright/roster_ledger.py` from `roster.json` (status `{roster['status']}`, approved by {roster['approval']['owner']} on {roster['approval']['local_date']} {roster['approval']['timezone']}) and the kit snapshot (public {snapshot['public_retrieved_at']}, hidden inventory {snapshot['hidden_inventory_retrieved_at']}). Membership is owned by `roster.json`; this ledger only projects it and records discoveries.\n",
           "| Disposition | Count |\n|---|---:|"]
    for k in ("INCLUDE", "REFERENCE", "EXCLUDE", "DEFER"):
        out.append(f"| {k} | {counts.get(k, 0)} |")
    out.append(f"| Total records | {len(recs)} |\n")
    out.append("Explicit exclusions by instruction: " + "; ".join(roster["explicit_exclusions"]) + ". Named non-public exclusions: " +
               ", ".join(roster["approval"]["named_non_public_exclusions"]) + ". Explicit public H-rank inclusions: " +
               ", ".join(roster["approval"]["explicit_public_h_inclusions"]) + ". Shiroi Youso (included) and Youso Shiroi (excluded) are distinct records.\n")
    out.append("## Every census record\n")
    out.append("| Review | Bloodline | Id | Rank | Hidden | Public / hidden jutsu | Decision | Basis | Planning state |\n|---|---|---|---|---|---:|---|---|---|")
    trees_dir = os.path.join(L.DESIGN_DIR, "trees")
    for r in recs:
        bid = r["bloodline_id"]
        slug = L.slugify(r["name"])
        if bid in reference:
            state = "worked reference (examples/taiyo_kami.*)"
        elif bid in approved:
            tpath = os.path.join(trees_dir, slug + ".json")
            state = f"tree: trees/{slug}.json" if os.path.exists(tpath) else "approved; tree pending"
        else:
            state = "outside approved batch"
        out.append(f"| {r['review_id']} | {r['name'].strip()} | `{bid}` | {r['rank']} | {'yes' if r['hidden'] else 'no'} | {r['public_jutsu_count']} / {r['hidden_jutsu_count']} | {r['owner_decision']} | {r['decision_basis']} | {state} |")
    # discoveries
    out.append("\n## Discovered during planning (not roster changes)\n")
    disc = []
    for r in recs:
        if r["name"] != r["name"].strip():
            disc.append(f"`{r['review_id']}` **{r['name'].strip()}**: the captured bloodline name carries a trailing space (`{r['name']!r}`); keep the stable id, do not rename.")
    for bid, ent in idx.items():
        kit = ent["kit"]; rec = ent["record"]
        for j in kit.get("hidden_jutsu", []) + kit.get("public_jutsu", []):
            if j.get("jutsuType") != "BLOODLINE":
                disc.append(f"`{rec['review_id']}` **{kit['bloodline']['name'].strip()}**: linked jutsu *{j['name']}* (`{j['id']}`) has jutsuType `{j.get('jutsuType')}`, hidden={j.get('hidden')}; it is counted in the kit because the capture linked it by bloodlineId.")
    seen = set()
    for key in ("injected_dependencies_public", "injected_dependencies_extended"):
        for jid, v in snapshot.get(key, {}).items():
            if jid in seen:
                continue
            seen.add(jid)
            rec = v.get("data", v)
            disc.append(f"Injected child *{rec.get('name')}* (`{jid}`, type {rec.get('jutsuType')}, bloodlineId `{rec.get('bloodlineId') or ''}`) is reachable through an `injectjutsus` row; it is not a roster record and is covered by the dossiers' injected-children tables.")
    for d in disc:
        out.append(f"- {d}")
    out.append("\nNo new bloodline records were discovered beyond the 95 captured; Borrowed Awakening still has no resolved id in this census. Any membership change requires a roster amendment (`new_or_changed_membership_requires_roster_amendment: true`).\n")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    txt = build()
    if args.check:
        cur = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else None
        if cur != txt:
            print(f"STALE {OUT}")
            return 2
        print("roster ledger current")
        return 0
    L.write_text(OUT, txt)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
