#!/usr/bin/env python3
"""content_workstream.py - repository-backed content workstreams.

A top-level planning conversation commits a workstream; later specialised
conversations initialize from it. The repository, not a predecessor chat, is the
bridge between them.

    Initialize session from repo. Workstream: One Perfect Crop. Task: art.scene_characters.

From that one line a fresh session reconstructs the project, what is already
done, the selected task's scope, its dependencies, the exact repository
resources to read, the expected outputs, the completion gates, and where results
get recorded.

WHAT THIS IS NOT
  The roadmap is coordination state, never canon. It owns task decomposition,
  status, dependencies, pointers, deliverables, gates and evidence. It does not
  restate quest mechanics, prose, doctrine, engine laws, generated contracts or
  art specs - those keep their existing owners and the roadmap links to them.
  It does not replace state/active-context.md or state/status.json; it is
  content-project coordination beneath the existing repository operating system,
  and docs/00_INDEX.md remains the only precedence table.

LAYOUT
  state/workstreams/INDEX.md               generated projection of all workstreams
  state/workstreams/<slug>/roadmap.json    canonical coordination source (edit this)
  state/workstreams/<slug>/ROADMAP.md      generated projection

COMMANDS
  validate <path>|--all     schema + graph + status + resource invariants
  render <path>|--all       regenerate ROADMAP.md and INDEX.md deterministically
  render --check            fail if a generated projection is stale
  list                      every workstream with progress and current work
  next <slug>               executable and blocked tasks right now
  init <slug> --task <id>   the session initialization packet
  --selftest                socket-free tests over synthesized fixtures

Stdlib only, deterministic, socket-free. Nothing here contacts ChatGPT, GitHub,
the TNR API, or any image generator.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

SCHEMA = "tnr.content_workstream"
VERSION = 1

WORKSTREAMS_DIR = "state/workstreams"

TASK_STATUSES = (
    "PLANNED",
    "READY",
    "IN_PROGRESS",
    "BLOCKED",
    "REVIEW",
    "COMPLETE",
    "SKIPPED",
    "SUPERSEDED",
)
WORKSTREAM_STATUSES = ("PLANNED", "ACTIVE", "BLOCKED", "COMPLETE", "SUPERSEDED")

# A dependency in one of these is settled enough for a dependent task to start.
SATISFIED = ("COMPLETE", "SKIPPED", "SUPERSEDED")
# These statuses assert the task is executable now, so their inputs must be real.
EXECUTABLE = ("READY", "IN_PROGRESS")
# Statuses that close a task and therefore owe evidence.
CLOSING = ("COMPLETE",)

AREAS = (
    "design",
    "prose",
    "research",
    "art",
    "admin",
    "build",
    "review",
    "production",
    "tooling",
)

EVIDENCE_KINDS = (
    "path",       # a committed repository artifact
    "capture",    # a committed capture/result bundle
    "sha",        # an exact commit SHA
    "decision",   # a recorded user/content-admin decision
    "validator",  # a named validator/gate result
    "approval",   # recorded user acceptance
    "note",       # anything else, used sparingly
)

# Inputs that live here are not durable and must never back a READY task.
EPHEMERAL_MARKERS = ("/mnt/data", "/tmp/", "sandbox:", "file:///", "~/", "attachment:")

PROGRESS_ORDER = {name: i for i, name in enumerate(TASK_STATUSES)}

GENERATED_BANNER = (
    "<!-- GENERATED by scripts/content_workstream.py - edit roadmap.json, then "
    "`python3 scripts/content_workstream.py render --all`. Never edit this file. -->"
)


def repo_root_default() -> Path:
    here = Path(__file__).resolve().parents[1]
    if (here / "docs" / "00_INDEX.md").exists():
        return here
    return Path.cwd()


# --------------------------------------------------------------------------
# loading
# --------------------------------------------------------------------------


def load_roadmap(path: Path) -> dict:
    try:
        with path.open(encoding="utf-8") as handle:
            return json.load(handle)
    except FileNotFoundError:
        raise SystemExit(f"content_workstream: roadmap not found: {path}")
    except json.JSONDecodeError as exc:
        raise SystemExit(f"content_workstream: {path} is not valid JSON: {exc}")


def roadmap_paths(repo_root: Path) -> list[Path]:
    base = repo_root / WORKSTREAMS_DIR
    if not base.is_dir():
        return []
    return sorted(p for p in base.glob("*/roadmap.json") if p.is_file())


def resolve_workstream(repo_root: Path, name: str) -> Path:
    """Match by slug, then unambiguously by title. Deterministic either way."""
    direct = repo_root / WORKSTREAMS_DIR / name / "roadmap.json"
    if direct.is_file():
        return direct
    wanted = name.strip().lower()
    hits = []
    for path in roadmap_paths(repo_root):
        data = load_roadmap(path)
        if data.get("slug", "").lower() == wanted or str(data.get("title", "")).lower() == wanted:
            hits.append(path)
    if len(hits) == 1:
        return hits[0]
    if not hits:
        known = ", ".join(p.parent.name for p in roadmap_paths(repo_root)) or "(none)"
        raise SystemExit(f"content_workstream: no workstream matches {name!r}. Known: {known}")
    raise SystemExit(f"content_workstream: {name!r} is ambiguous; use the slug")


# --------------------------------------------------------------------------
# validation
# --------------------------------------------------------------------------


def _bad_path(value: str) -> str | None:
    """Return a reason string if this is not a durable repository-relative path."""
    if not isinstance(value, str) or not value.strip():
        return "empty path"
    for marker in EPHEMERAL_MARKERS:
        if marker in value:
            return f"points at ephemeral/sandbox location ({marker!r}); not durable repository evidence"
    if value.startswith("/") or (len(value) > 1 and value[1] == ":"):
        return "absolute filesystem path; use a repository-relative path"
    if ".." in Path(value).parts:
        return "contains '..'"
    return None


def _cycles(tasks: list[dict]) -> list[list[str]]:
    graph = {t["id"]: [d for d in t.get("depends_on", []) if isinstance(d, str)] for t in tasks if t.get("id")}
    found: list[list[str]] = []
    state: dict[str, int] = {}

    def walk(node: str, trail: list[str]) -> None:
        state[node] = 1
        for nxt in graph.get(node, []):
            if nxt not in graph:
                continue
            if state.get(nxt) == 1:
                cycle = trail[trail.index(nxt):] + [nxt] if nxt in trail else [nxt, node, nxt]
                if cycle not in found:
                    found.append(cycle)
            elif state.get(nxt, 0) == 0:
                walk(nxt, trail + [nxt])
        state[node] = 2

    for node in sorted(graph):
        if state.get(node, 0) == 0:
            walk(node, [node])
    return found


def validate(roadmap: dict, repo_root: Path, source: Path | None = None) -> list[str]:
    errors: list[str] = []

    def bad(msg: str) -> None:
        errors.append(msg)

    if roadmap.get("schema") != SCHEMA:
        bad(f"schema must be {SCHEMA!r}, found {roadmap.get('schema')!r}")
    if roadmap.get("version") != VERSION:
        bad(f"version must be {VERSION}, found {roadmap.get('version')!r}")

    for field in ("slug", "title", "content_type", "status", "objective"):
        if not roadmap.get(field):
            bad(f"workstream field {field!r} is required")

    slug = roadmap.get("slug")
    if isinstance(slug, str) and slug:
        if not slug.replace("_", "").replace("-", "").isalnum():
            bad(f"slug {slug!r} must be alphanumeric with _ or -")
        if source is not None and source.parent.name != slug:
            bad(f"slug {slug!r} does not match its directory {source.parent.name!r}")

    if roadmap.get("status") not in WORKSTREAM_STATUSES:
        bad(f"workstream status must be one of {', '.join(WORKSTREAM_STATUSES)}")

    for position, res in enumerate(roadmap.get("resources", [])):
        label = f"resources[{position}]"
        if not isinstance(res, dict):
            bad(f"{label} is not an object")
            continue
        reason = _bad_path(res.get("path", ""))
        if reason:
            bad(f"{label}: {reason}")
        elif not (repo_root / res["path"]).exists():
            bad(f"{label}: {res['path']} does not exist in the repository")
        if not res.get("why"):
            bad(f"{label}: 'why' is required - a pointer without a reason is noise")

    tasks = roadmap.get("tasks")
    if not isinstance(tasks, list) or not tasks:
        bad("tasks must be a non-empty array")
        return errors

    seen: dict[str, int] = {}
    by_id: dict[str, dict] = {}
    for position, task in enumerate(tasks):
        if not isinstance(task, dict):
            bad(f"tasks[{position}] is not an object")
            continue
        tid = task.get("id")
        if not tid:
            bad(f"tasks[{position}]: id is required")
            continue
        if tid in seen:
            bad(f"task {tid!r}: duplicate task id (also at index {seen[tid]})")
        seen[tid] = position
        by_id[tid] = task

    for tid, task in by_id.items():
        for field in ("title", "area", "status", "owner", "objective"):
            if not task.get(field):
                bad(f"task {tid!r}: field {field!r} is required")

        status = task.get("status")
        if status not in TASK_STATUSES:
            bad(f"task {tid!r}: status must be one of {', '.join(TASK_STATUSES)}")
        if task.get("area") not in AREAS:
            bad(f"task {tid!r}: area must be one of {', '.join(AREAS)}")

        for field in ("scope", "deliverables", "completion_gates"):
            value = task.get(field)
            if not isinstance(value, list) or not value:
                bad(f"task {tid!r}: {field} must be a non-empty list")

        deps = task.get("depends_on", [])
        if not isinstance(deps, list):
            bad(f"task {tid!r}: depends_on must be a list")
            deps = []
        for dep in deps:
            if dep == tid:
                bad(f"task {tid!r}: depends on itself")
            elif dep not in by_id:
                bad(f"task {tid!r}: depends_on references unknown task {dep!r}")

        unmet = [d for d in deps if d in by_id and by_id[d].get("status") not in SATISFIED]
        if status in EXECUTABLE and unmet:
            named = ", ".join(f"{d} ({by_id[d].get('status')})" for d in unmet)
            bad(f"task {tid!r} is {status} but depends on unfinished {named}")
        if status in CLOSING and unmet:
            bad(f"task {tid!r} is COMPLETE but depends on unfinished {', '.join(unmet)}")

        resources = task.get("required_resources", [])
        if not isinstance(resources, list):
            bad(f"task {tid!r}: required_resources must be a list")
            resources = []
        for position, res in enumerate(resources):
            label = f"task {tid!r} required_resources[{position}]"
            if not isinstance(res, dict):
                bad(f"{label} is not an object")
                continue
            reason = _bad_path(res.get("path", ""))
            if reason:
                bad(f"{label}: {reason}")
                continue
            if not res.get("why"):
                bad(f"{label}: 'why' is required")
            if not (repo_root / res["path"]).exists():
                if status in EXECUTABLE:
                    bad(
                        f"{label}: {res['path']} does not exist, so {tid!r} cannot be {status}. "
                        "READY means a fresh session can execute it from repository evidence alone."
                    )
                else:
                    bad(f"{label}: {res['path']} does not exist in the repository")

        blockers = task.get("blockers") or []
        decisions = task.get("open_decisions") or []
        if status == "BLOCKED" and not (blockers or decisions):
            bad(f"task {tid!r} is BLOCKED but names no blocker or open decision")
        if status in EXECUTABLE and blockers:
            bad(f"task {tid!r} is {status} but still carries blockers: {'; '.join(map(str, blockers))}")

        evidence = task.get("evidence") or []
        if not isinstance(evidence, list):
            bad(f"task {tid!r}: evidence must be a list")
            evidence = []
        if status in CLOSING and not evidence:
            bad(
                f"task {tid!r} is COMPLETE with no evidence. A conversation saying it is done "
                "is not evidence; record artifacts, captures, SHAs, validator results or approval."
            )
        if status == "PLANNED" and evidence:
            bad(f"task {tid!r} is PLANNED but already carries evidence")
        for position, item in enumerate(evidence):
            label = f"task {tid!r} evidence[{position}]"
            if not isinstance(item, dict):
                bad(f"{label} is not an object")
                continue
            kind = item.get("kind")
            if kind not in EVIDENCE_KINDS:
                bad(f"{label}: kind must be one of {', '.join(EVIDENCE_KINDS)}")
            if not item.get("ref"):
                bad(f"{label}: 'ref' is required")
                continue
            if kind in ("path", "capture"):
                reason = _bad_path(item["ref"])
                if reason:
                    bad(f"{label}: {reason}")
                elif not (repo_root / item["ref"]).exists():
                    bad(f"{label}: {item['ref']} does not exist in the repository")

        if status == "IN_PROGRESS" and not task.get("resume_note"):
            bad(
                f"task {tid!r} is IN_PROGRESS without a resume_note. Partial work needs a durable "
                "note or the next session restarts it."
            )

    for cycle in _cycles([t for t in tasks if isinstance(t, dict) and t.get("id")]):
        bad(f"dependency cycle: {' -> '.join(cycle)}")

    return errors


# --------------------------------------------------------------------------
# derived views
# --------------------------------------------------------------------------


def progress(roadmap: dict) -> dict[str, int]:
    counts = {name: 0 for name in TASK_STATUSES}
    for task in roadmap.get("tasks", []):
        status = task.get("status")
        if status in counts:
            counts[status] += 1
    return counts


def progress_line(roadmap: dict) -> str:
    counts = progress(roadmap)
    total = sum(counts.values())
    done = counts["COMPLETE"] + counts["SKIPPED"]
    parts = [f"{name.lower()} {n}" for name, n in counts.items() if n]
    return f"{done}/{total} settled - " + ", ".join(parts)


def tasks_by_status(roadmap: dict, *statuses: str) -> list[dict]:
    return [t for t in roadmap.get("tasks", []) if t.get("status") in statuses]


def unmet_deps(roadmap: dict, task: dict) -> list[tuple[str, str]]:
    by_id = {t["id"]: t for t in roadmap.get("tasks", []) if t.get("id")}
    out = []
    for dep in task.get("depends_on", []):
        other = by_id.get(dep)
        status = other.get("status") if other else "UNKNOWN"
        if status not in SATISFIED:
            out.append((dep, status))
    return out


def find_task(roadmap: dict, task_id: str) -> dict:
    wanted = task_id.strip().lower()
    exact = [t for t in roadmap.get("tasks", []) if str(t.get("id", "")).lower() == wanted]
    if len(exact) == 1:
        return exact[0]
    titled = [t for t in roadmap.get("tasks", []) if str(t.get("title", "")).lower() == wanted]
    if len(titled) == 1:
        return titled[0]
    known = ", ".join(t.get("id", "?") for t in roadmap.get("tasks", []))
    raise SystemExit(f"content_workstream: no task matches {task_id!r}. Known task ids: {known}")


# --------------------------------------------------------------------------
# rendering
# --------------------------------------------------------------------------


def render_roadmap_md(roadmap: dict) -> str:
    out: list[str] = [GENERATED_BANNER, ""]
    out.append(f"# {roadmap['title']} - content workstream roadmap")
    out.append("")
    out.append(f"- **Slug:** `{roadmap['slug']}`")
    out.append(f"- **Content type:** {roadmap['content_type']}")
    out.append(f"- **Status:** {roadmap['status']}")
    out.append(f"- **Progress:** {progress_line(roadmap)}")
    out.append("")
    out.append(f"{roadmap['objective']}")
    out.append("")
    out.append(
        "This roadmap is **coordination state, not canon.** It points at the authoritative "
        "sources below and never restates them. `docs/00_INDEX.md` remains the only precedence "
        "table; `state/active-context.md` and `state/status.json` remain the global session state."
    )
    out.append("")

    resources = roadmap.get("resources", [])
    if resources:
        out.append("## Workstream resources")
        out.append("")
        out.append("| Path | Why |")
        out.append("| --- | --- |")
        for res in resources:
            out.append(f"| `{res['path']}` | {res['why']} |")
        out.append("")

    out.append("## Tasks")
    out.append("")
    out.append("| Task | Status | Owner | Depends on | Scope |")
    out.append("| --- | --- | --- | --- | --- |")
    for task in roadmap["tasks"]:
        deps = ", ".join(f"`{d}`" for d in task.get("depends_on", [])) or "-"
        scope = str(task.get("scope", ["-"])[0])
        out.append(
            f"| `{task['id']}` | {task['status']} | {task['owner']} | {deps} | {scope} |"
        )
    out.append("")

    ready = tasks_by_status(roadmap, "READY")
    in_progress = tasks_by_status(roadmap, "IN_PROGRESS")
    if ready or in_progress:
        out.append("## Executable now")
        out.append("")
        for task in in_progress:
            out.append(f"- **`{task['id']}`** (IN_PROGRESS) - {task['title']}")
            out.append(f"  - resume: {task.get('resume_note', '')}")
        for task in ready:
            out.append(f"- **`{task['id']}`** (READY) - {task['title']}")
            out.append(
                f"  - `python3 scripts/content_workstream.py init {roadmap['slug']} --task {task['id']}`"
            )
        out.append("")

    blocked = tasks_by_status(roadmap, "BLOCKED")
    if blocked:
        out.append("## Blocked")
        out.append("")
        for task in blocked:
            out.append(f"### `{task['id']}` - {task['title']}")
            out.append("")
            for item in task.get("blockers", []):
                out.append(f"- BLOCKER: {item}")
            for item in task.get("open_decisions", []):
                out.append(f"- OPEN DECISION (user-owned): {item}")
            out.append("")

    open_elsewhere = [
        (t, d)
        for t in roadmap["tasks"]
        if t.get("status") != "BLOCKED"
        for d in t.get("open_decisions", [])
    ]
    if open_elsewhere:
        out.append("## Other open decisions")
        out.append("")
        for task, decision in open_elsewhere:
            out.append(f"- `{task['id']}`: {decision}")
        out.append("")

    waiting = [
        t for t in roadmap["tasks"] if t.get("status") == "PLANNED" and unmet_deps(roadmap, t)
    ]
    if waiting:
        out.append("## Waiting on dependencies")
        out.append("")
        for task in waiting:
            unmet = ", ".join(f"`{d}` ({s})" for d, s in unmet_deps(roadmap, task))
            out.append(f"- `{task['id']}` - waiting on {unmet}")
        out.append("")

    done = tasks_by_status(roadmap, "COMPLETE", "SKIPPED", "SUPERSEDED")
    if done:
        out.append("## Completed, with evidence")
        out.append("")
        for task in done:
            out.append(f"### `{task['id']}` - {task['title']} ({task['status']})")
            out.append("")
            for item in task.get("evidence", []):
                note = f" - {item['note']}" if item.get("note") else ""
                if item.get("kind") in ("path", "capture"):
                    out.append(f"- {item['kind']}: `{item['ref']}`{note}")
                else:
                    out.append(f"- {item['kind']}: {item['ref']}{note}")
            out.append("")

    out.append("## Task detail")
    out.append("")
    for task in roadmap["tasks"]:
        out.append(f"### `{task['id']}` - {task['title']}")
        out.append("")
        role = f", lead role {task['lead_role']}" if task.get("lead_role") else ""
        out.append(f"**{task['status']}** - area {task['area']}, owner {task['owner']}{role}")
        out.append("")
        out.append(task["objective"])
        out.append("")
        out.append("**Scope**")
        out.append("")
        for item in task.get("scope", []):
            out.append(f"- {item}")
        out.append("")
        if task.get("out_of_scope"):
            out.append("**Out of scope**")
            out.append("")
            for item in task["out_of_scope"]:
                out.append(f"- {item}")
            out.append("")
        if task.get("required_resources"):
            out.append("**Required resources**")
            out.append("")
            for res in task["required_resources"]:
                out.append(f"- `{res['path']}` - {res['why']}")
            out.append("")
        out.append("**Deliverables**")
        out.append("")
        for item in task.get("deliverables", []):
            out.append(f"- {item}")
        out.append("")
        out.append("**Completion gates**")
        out.append("")
        for item in task.get("completion_gates", []):
            out.append(f"- {item}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def render_index_md(roadmaps: list[dict]) -> str:
    out: list[str] = [GENERATED_BANNER, ""]
    out.append("# Content workstreams")
    out.append("")
    out.append(
        "Coordination projection for repository-backed content workstreams. This is **not** the "
        "global board: `state/active-context.md` and `state/status.json` remain the session state, "
        "and `docs/00_INDEX.md` remains the precedence table. The workflow is "
        "`docs/workflows/CONTENT_WORKSTREAM.md`."
    )
    out.append("")
    if not roadmaps:
        out.append("_No workstreams yet._")
        return "\n".join(out) + "\n"

    out.append("| Workstream | Slug | Type | Status | Progress | Roadmap |")
    out.append("| --- | --- | --- | --- | --- | --- |")
    for roadmap in roadmaps:
        out.append(
            f"| {roadmap['title']} | `{roadmap['slug']}` | {roadmap['content_type']} | "
            f"{roadmap['status']} | {progress_line(roadmap)} | "
            f"[`ROADMAP.md`]({roadmap['slug']}/ROADMAP.md) |"
        )
    out.append("")

    for roadmap in roadmaps:
        out.append(f"## {roadmap['title']}")
        out.append("")
        out.append(f"`{WORKSTREAMS_DIR}/{roadmap['slug']}/roadmap.json`")
        out.append("")
        current = tasks_by_status(roadmap, "IN_PROGRESS") + tasks_by_status(roadmap, "READY")
        if current:
            out.append("**Executable now**")
            out.append("")
            for task in current:
                out.append(f"- `{task['id']}` ({task['status']}) - {task['title']}")
            out.append("")
        else:
            out.append("**Executable now:** none.")
            out.append("")
        blocked = tasks_by_status(roadmap, "BLOCKED")
        if blocked:
            out.append("**Blocked**")
            out.append("")
            for task in blocked:
                reasons = (task.get("blockers") or []) + (task.get("open_decisions") or [])
                out.append(f"- `{task['id']}` - {reasons[0] if reasons else 'see roadmap'}")
            out.append("")
        out.append(
            f"Start a session: `python3 scripts/content_workstream.py init {roadmap['slug']} --task <id>`"
        )
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def render_all(repo_root: Path, check: bool = False, only: Path | None = None) -> int:
    paths = [only] if only else roadmap_paths(repo_root)
    roadmaps = [load_roadmap(p) for p in roadmap_paths(repo_root)]
    stale: list[str] = []
    wrote: list[str] = []

    def emit(target: Path, text: str) -> None:
        rel = target.relative_to(repo_root).as_posix()
        current = target.read_text(encoding="utf-8") if target.exists() else None
        if current == text:
            print(f"same   {rel}")
            return
        if check:
            print(f"STALE  {rel}")
            stale.append(rel)
            return
        target.write_text(text, encoding="utf-8")
        print(f"wrote  {rel}")
        wrote.append(rel)

    for path in paths:
        roadmap = load_roadmap(path)
        emit(path.parent / "ROADMAP.md", render_roadmap_md(roadmap))

    index = repo_root / WORKSTREAMS_DIR / "INDEX.md"
    index.parent.mkdir(parents=True, exist_ok=True)
    emit(index, render_index_md(roadmaps))

    if check and stale:
        print(f"\n{len(stale)} generated projection(s) are stale; run render --all", file=sys.stderr)
        return 1
    print("\n" + ("all projections current (exit 0)" if check else f"{len(wrote)} file(s) written"))
    return 0


# --------------------------------------------------------------------------
# init - the session initialization packet
# --------------------------------------------------------------------------


GLOBAL_AUTHORITY = [
    ("state/active-context.md", "current global session state - read first"),
    ("state/status.json", "the board"),
    ("docs/00_INDEX.md", "precedence, evidence tiers, task routing - arbitrates disagreements"),
    ("docs/RULINGS.md", "durable user rulings"),
    ("docs/workflows/CONTENT_WORKSTREAM.md", "how to work and close out a workstream task"),
]


def init_packet(roadmap: dict, task: dict, repo_root: Path) -> tuple[list[str], bool]:
    out: list[str] = []
    ok = True
    status = task.get("status")

    out.append(f"SESSION INIT - {roadmap['title']} / {task['id']}")
    out.append("=" * len(f"SESSION INIT - {roadmap['title']} / {task['id']}"))
    out.append("")
    out.append(f"Workstream : {roadmap['title']} (`{roadmap['slug']}`), {roadmap['content_type']}, {roadmap['status']}")
    out.append(f"Task       : {task['title']}")
    out.append(f"Status     : {status}")
    out.append(f"Area/owner : {task['area']} / {task['owner']}" + (f" / lead role {task['lead_role']}" if task.get("lead_role") else ""))
    out.append(f"Progress   : {progress_line(roadmap)}")
    out.append("")

    unmet = unmet_deps(roadmap, task)
    if status not in EXECUTABLE:
        ok = False
        out.append("STOP - this task is not executable.")
        out.append("")
        out.append(f"  Its status is {status}, not READY or IN_PROGRESS.")
        if unmet:
            out.append("  Unfinished dependencies:")
            for dep, dep_status in unmet:
                out.append(f"    - {dep} is {dep_status}")
        for item in task.get("blockers", []):
            out.append(f"  BLOCKER: {item}")
        for item in task.get("open_decisions", []):
            out.append(f"  OPEN DECISION (user-owned): {item}")
        out.append("")
        ready = tasks_by_status(roadmap, "READY") + tasks_by_status(roadmap, "IN_PROGRESS")
        if ready:
            out.append("  Executable instead:")
            for other in ready:
                out.append(f"    - {other['id']} ({other['status']}) - {other['title']}")
        else:
            out.append("  Nothing in this workstream is executable right now.")
        out.append("")
        out.append("  Do not start this task by inventing its missing inputs.")
        return out, ok

    out.append("OBJECTIVE")
    out.append("")
    out.append(f"  {task['objective']}")
    out.append("")
    out.append("SCOPE - this session, and only this")
    out.append("")
    for item in task.get("scope", []):
        out.append(f"  - {item}")
    if task.get("out_of_scope"):
        out.append("")
        out.append("  Out of scope:")
        for item in task["out_of_scope"]:
            out.append(f"  - {item}")
    out.append("")

    if task.get("resume_note"):
        out.append("RESUME NOTE - work already in progress")
        out.append("")
        out.append(f"  {task['resume_note']}")
        out.append("")

    out.append("DEPENDENCIES")
    out.append("")
    if task.get("depends_on"):
        by_id = {t["id"]: t for t in roadmap["tasks"]}
        for dep in task["depends_on"]:
            other = by_id.get(dep, {})
            out.append(f"  {dep}: {other.get('status', 'UNKNOWN')} - {other.get('title', '?')}")
    else:
        out.append("  none")
    out.append("")

    out.append("READ FIRST - global authority (verify the live repository head before substantive work)")
    out.append("")
    for path, why in GLOBAL_AUTHORITY:
        mark = " " if (repo_root / path).exists() else "!"
        out.append(f" {mark} {path}")
        out.append(f"     {why}")
    out.append("")

    if roadmap.get("resources"):
        out.append("READ - workstream resources")
        out.append("")
        for res in roadmap["resources"]:
            mark = " " if (repo_root / res["path"]).exists() else "!"
            out.append(f" {mark} {res['path']}")
            out.append(f"     {res['why']}")
        out.append("")

    already = {res["path"] for res in roadmap.get("resources", [])}
    task_only = [res for res in task.get("required_resources", []) if res["path"] not in already]
    if task_only:
        out.append("READ - required for this task, beyond the workstream resources above")
        out.append("")
        for res in task_only:
            mark = " " if (repo_root / res["path"]).exists() else "!"
            out.append(f" {mark} {res['path']}")
            out.append(f"     {res['why']}")
        out.append("")

    upstream = [
        t
        for t in roadmap["tasks"]
        if t["id"] in task.get("depends_on", []) and t.get("evidence")
    ]
    if upstream:
        out.append("UPSTREAM OUTPUTS already settled - build on these, do not redo them")
        out.append("")
        for other in upstream:
            out.append(f"  {other['id']} ({other['status']}):")
            for item in other["evidence"]:
                note = f" - {item['note']}" if item.get("note") else ""
                out.append(f"    {item['kind']}: {item['ref']}{note}")
        out.append("")

    out.append("DELIVERABLES")
    out.append("")
    for item in task.get("deliverables", []):
        out.append(f"  - {item}")
    out.append("")

    out.append("COMPLETION GATES - all of these, or the task is not COMPLETE")
    out.append("")
    for item in task.get("completion_gates", []):
        out.append(f"  - {item}")
    out.append("")

    decisions = task.get("open_decisions") or []
    if decisions:
        out.append("OPEN USER-OWNED DECISIONS - do not settle these yourself")
        out.append("")
        for item in decisions:
            out.append(f"  - {item}")
        out.append("")

    ws_open = [
        (t["id"], d)
        for t in roadmap["tasks"]
        if t["id"] != task["id"]
        for d in (t.get("open_decisions") or [])
    ]
    if ws_open:
        out.append("OPEN ELSEWHERE IN THE WORKSTREAM - context, not this session's work")
        out.append("")
        for tid, decision in ws_open:
            out.append(f"  - {tid}: {decision}")
        out.append("")

    out.append("RECORD RESULTS BACK INTO THE REPOSITORY")
    out.append("")
    out.append(f"  Source of record : {WORKSTREAMS_DIR}/{roadmap['slug']}/roadmap.json (edit this)")
    out.append("  At a durable stopping point, set this task's status and evidence, and if the")
    out.append("  work is partial, set IN_PROGRESS with a concise resume_note. Then:")
    out.append("")
    out.append("    python3 scripts/content_workstream.py validate --all")
    out.append("    python3 scripts/content_workstream.py render --all")
    out.append("")
    out.append("  COMPLETE requires evidence a later session can verify from the repository:")
    out.append("  committed artifact paths, accepted filenames, QC/preflight results, captures,")
    out.append("  exact SHAs, validator results, or recorded user acceptance. Saying it is")
    out.append("  finished is not evidence.")
    out.append("")
    out.append("BOUNDARIES")
    out.append("")
    out.append("  - The roadmap is coordination state. Canon stays with its owner; if this task")
    out.append("    needs a canonical change, change the owner, do not restate it here.")
    out.append("  - Balance, rewards, rarity, publishing, final art direction and final content")
    out.append("    acceptance are the user's. Propose; do not settle.")
    out.append("  - The user is the only live-game actor. No game write happens in this session.")
    return out, ok


# --------------------------------------------------------------------------
# selftest
# --------------------------------------------------------------------------


def _valid_fixture(repo: Path) -> dict:
    return {
        "schema": SCHEMA,
        "version": VERSION,
        "slug": "fixture",
        "title": "Fixture Event",
        "content_type": "event",
        "status": "ACTIVE",
        "objective": "A fixture workstream.",
        "resources": [{"path": "docs/00_INDEX.md", "why": "precedence"}],
        "tasks": [
            {
                "id": "design.structure",
                "title": "Structure",
                "area": "design",
                "status": "COMPLETE",
                "owner": "ChatGPT",
                "objective": "Settle the route graph.",
                "depends_on": [],
                "scope": ["route graph"],
                "required_resources": [{"path": "docs/00_INDEX.md", "why": "precedence"}],
                "deliverables": ["a frozen graph"],
                "completion_gates": ["user approval"],
                "evidence": [{"kind": "path", "ref": "docs/00_INDEX.md", "note": "stand-in"}],
            },
            {
                "id": "art.scene_characters",
                "title": "Scene characters",
                "area": "art",
                "status": "READY",
                "owner": "ChatGPT",
                "lead_role": "Image Production",
                "objective": "Produce the scene characters.",
                "depends_on": ["design.structure"],
                "scope": ["all scene characters, one at a time"],
                "required_resources": [{"path": "docs/00_INDEX.md", "why": "precedence"}],
                "deliverables": ["accepted webp files"],
                "completion_gates": ["preflight 0 errors"],
                "evidence": [],
            },
            {
                "id": "build.manifest",
                "title": "Manifest",
                "area": "build",
                "status": "PLANNED",
                "owner": "Fable",
                "objective": "Implement the manifest.",
                "depends_on": ["art.scene_characters"],
                "scope": ["manifest"],
                "required_resources": [],
                "deliverables": ["a validated manifest"],
                "completion_gates": ["validate.py 0 errors"],
                "evidence": [],
            },
        ],
    }


def selftest() -> int:
    import copy
    import tempfile

    failures: list[str] = []

    def want(condition: bool, label: str) -> None:
        print(("  ok   " if condition else "  FAIL ") + label)
        if not condition:
            failures.append(label)

    def has(errors: list[str], needle: str) -> bool:
        return any(needle in e for e in errors)

    with tempfile.TemporaryDirectory() as raw_tmp:
        repo = Path(raw_tmp) / "repo"
        (repo / "docs").mkdir(parents=True)
        (repo / "docs" / "00_INDEX.md").write_text("fixture", encoding="utf-8")
        (repo / WORKSTREAMS_DIR / "fixture").mkdir(parents=True)
        base = _valid_fixture(repo)
        source = repo / WORKSTREAMS_DIR / "fixture" / "roadmap.json"
        source.write_text(json.dumps(base), encoding="utf-8")

        print("a valid roadmap")
        want(validate(base, repo, source) == [], "a well-formed roadmap validates with zero errors")

        print("\ngraph faults")
        bad = copy.deepcopy(base)
        bad["tasks"][1]["id"] = "design.structure"
        want(has(validate(bad, repo, source), "duplicate task id"), "duplicate task ids are rejected")

        bad = copy.deepcopy(base)
        bad["tasks"][1]["depends_on"] = ["nope.missing"]
        want(has(validate(bad, repo, source), "unknown task"), "a missing dependency is rejected")

        bad = copy.deepcopy(base)
        bad["tasks"][0]["depends_on"] = ["build.manifest"]
        want(has(validate(bad, repo, source), "dependency cycle"), "a dependency cycle is detected")

        bad = copy.deepcopy(base)
        bad["tasks"][1]["depends_on"] = ["art.scene_characters"]
        want(has(validate(bad, repo, source), "depends on itself"), "self-dependency is rejected")

        print("\nstatus/dependency faults")
        bad = copy.deepcopy(base)
        bad["tasks"][0]["status"] = "PLANNED"
        bad["tasks"][0]["evidence"] = []
        want(
            has(validate(bad, repo, source), "READY but depends on unfinished"),
            "a READY task with an unfinished dependency is rejected",
        )

        bad = copy.deepcopy(base)
        bad["tasks"][0]["evidence"] = []
        want(has(validate(bad, repo, source), "COMPLETE with no evidence"), "a COMPLETE task without evidence is rejected")

        bad = copy.deepcopy(base)
        bad["tasks"][1]["status"] = "BLOCKED"
        want(has(validate(bad, repo, source), "names no blocker"), "a BLOCKED task without a blocker is rejected")

        bad = copy.deepcopy(base)
        bad["tasks"][1]["blockers"] = ["something"]
        want(has(validate(bad, repo, source), "still carries blockers"), "a READY task that still carries blockers is rejected")

        bad = copy.deepcopy(base)
        bad["tasks"][1]["status"] = "IN_PROGRESS"
        want(has(validate(bad, repo, source), "without a resume_note"), "an IN_PROGRESS task without a resume_note is rejected")

        bad = copy.deepcopy(base)
        bad["tasks"][1]["status"] = "NOPE"
        want(has(validate(bad, repo, source), "status must be one of"), "an unknown status is rejected")

        print("\nresource durability")
        bad = copy.deepcopy(base)
        bad["tasks"][1]["required_resources"] = [{"path": "docs/gone.md", "why": "x"}]
        want(
            has(validate(bad, repo, source), "cannot be READY"),
            "a READY task whose required resource is missing is rejected",
        )

        for sandbox in ("/mnt/data/art.zip", "/tmp/x.webp", "sandbox:/x.png", "~/x.png"):
            bad = copy.deepcopy(base)
            bad["tasks"][1]["required_resources"] = [{"path": sandbox, "why": "x"}]
            want(
                has(validate(bad, repo, source), "ephemeral") or has(validate(bad, repo, source), "absolute"),
                f"a sandbox/absolute resource path is rejected: {sandbox}",
            )

        bad = copy.deepcopy(base)
        bad["tasks"][1]["required_resources"] = [{"path": "docs/../../etc/passwd", "why": "x"}]
        want(has(validate(bad, repo, source), "contains '..'"), "a traversing resource path is rejected")

        bad = copy.deepcopy(base)
        bad["tasks"][0]["evidence"] = [{"kind": "path", "ref": "/mnt/data/out.zip"}]
        want(has(validate(bad, repo, source), "ephemeral"), "sandbox evidence is rejected")

        bad = copy.deepcopy(base)
        bad["tasks"][0]["evidence"] = [{"kind": "path", "ref": "docs/gone.md"}]
        want(has(validate(bad, repo, source), "does not exist"), "evidence pointing at a missing file is rejected")

        bad = copy.deepcopy(base)
        bad["slug"] = "other"
        want(has(validate(bad, repo, source), "does not match its directory"), "a slug/directory mismatch is rejected")

        bad = copy.deepcopy(base)
        bad["version"] = 99
        want(has(validate(bad, repo, source), "version must be"), "a wrong schema version is rejected")

        print("\ndeterminism")
        want(render_roadmap_md(base) == render_roadmap_md(base), "ROADMAP render is deterministic")
        want(render_index_md([base]) == render_index_md([base]), "INDEX render is deterministic")
        want(GENERATED_BANNER in render_roadmap_md(base), "the ROADMAP says it is generated")
        want(GENERATED_BANNER in render_index_md([base]), "the INDEX says it is generated")
        reordered = copy.deepcopy(base)
        reordered["resources"] = list(base["resources"])
        want(render_roadmap_md(reordered) == render_roadmap_md(base), "render depends only on roadmap content")

        print("\ninit packets")
        packet, ok = init_packet(base, find_task(base, "art.scene_characters"), repo)
        text = "\n".join(packet)
        want(ok, "a READY task initializes")
        want(text == "\n".join(init_packet(base, find_task(base, "art.scene_characters"), repo)[0]), "init output is deterministic")
        for needle in ("OBJECTIVE", "SCOPE", "DEPENDENCIES", "READ FIRST", "DELIVERABLES", "COMPLETION GATES", "RECORD RESULTS"):
            want(needle in text, f"the packet carries the {needle} section")
        want("docs/00_INDEX.md" in text, "the packet routes the global precedence file")
        want("design.structure: COMPLETE" in text, "the packet reports upstream dependency status")

        packet, ok = init_packet(base, find_task(base, "build.manifest"), repo)
        text = "\n".join(packet)
        want(not ok, "a PLANNED downstream task refuses to initialize")
        want("STOP" in text and "art.scene_characters is READY" in text, "the refusal names the unfinished dependency")
        want("Executable instead" in text, "the refusal offers an actionable alternative")

        blocked = copy.deepcopy(base)
        blocked["tasks"][1]["status"] = "BLOCKED"
        blocked["tasks"][1]["blockers"] = ["bytes were never committed"]
        packet, ok = init_packet(blocked, find_task(blocked, "art.scene_characters"), repo)
        want(not ok and "bytes were never committed" in "\n".join(packet), "a BLOCKED task refuses and states the blocker")

        print("\nlookup")
        want(find_task(base, "ART.SCENE_CHARACTERS")["id"] == "art.scene_characters", "task lookup is case-insensitive")
        want(resolve_workstream(repo, "fixture") == source, "workstream resolves by slug")
        want(resolve_workstream(repo, "Fixture Event") == source, "workstream resolves by unambiguous title")

    print()
    if failures:
        print(f"{len(failures)} FAILED")
        for label in failures:
            print(f"  - {label}")
        return 1
    print("content_workstream selftest: all checks passed")
    return 0


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--selftest", action="store_true")
    parser.add_argument("--repo-root", type=Path, default=None)
    sub = parser.add_subparsers(dest="command")

    p_validate = sub.add_parser("validate", help="validate a roadmap")
    p_validate.add_argument("path", nargs="?", type=Path)
    p_validate.add_argument("--all", action="store_true")

    p_render = sub.add_parser("render", help="regenerate ROADMAP.md and INDEX.md")
    p_render.add_argument("path", nargs="?", type=Path)
    p_render.add_argument("--all", action="store_true")
    p_render.add_argument("--check", action="store_true", help="fail if a projection is stale")

    sub.add_parser("list", help="list workstreams")

    p_next = sub.add_parser("next", help="show executable and blocked tasks")
    p_next.add_argument("workstream")

    p_init = sub.add_parser("init", help="print the session initialization packet")
    p_init.add_argument("workstream")
    p_init.add_argument("--task", required=True)

    args = parser.parse_args(argv)
    if args.selftest:
        return selftest()
    if not args.command:
        parser.print_help()
        return 2

    repo_root = (args.repo_root or repo_root_default()).resolve()

    if args.command == "validate":
        if args.all or not args.path:
            paths = roadmap_paths(repo_root)
            if not paths:
                print("no workstreams found")
                return 0
        else:
            paths = [args.path if args.path.is_absolute() else repo_root / args.path]
        failed = 0
        for path in paths:
            roadmap = load_roadmap(path)
            errors = validate(roadmap, repo_root, path)
            rel = path.relative_to(repo_root).as_posix() if path.is_relative_to(repo_root) else str(path)
            if errors:
                failed += 1
                print(f"FAIL  {rel}  {len(errors)} error(s)", file=sys.stderr)
                for err in errors:
                    print(f"  - {err}", file=sys.stderr)
            else:
                print(f"ok    {rel}  {len(roadmap['tasks'])} tasks, {progress_line(roadmap)}")
        if failed:
            print(f"\n{failed} roadmap(s) failed validation", file=sys.stderr)
            return 1
        print(f"\n{len(paths)} roadmap(s) valid (exit 0)")
        return 0

    if args.command == "render":
        only = None
        if args.path and not args.all:
            only = args.path if args.path.is_absolute() else repo_root / args.path
        return render_all(repo_root, check=args.check, only=only)

    if args.command == "list":
        paths = roadmap_paths(repo_root)
        if not paths:
            print("no workstreams found")
            return 0
        for path in paths:
            roadmap = load_roadmap(path)
            print(f"{roadmap['slug']}  -  {roadmap['title']}  [{roadmap['status']}]")
            print(f"    {roadmap['content_type']}, {progress_line(roadmap)}")
            current = tasks_by_status(roadmap, "IN_PROGRESS") + tasks_by_status(roadmap, "READY")
            print(f"    executable now: {', '.join(t['id'] for t in current) or 'none'}")
            blocked = tasks_by_status(roadmap, "BLOCKED")
            if blocked:
                print(f"    blocked:        {', '.join(t['id'] for t in blocked)}")
            print(f"    roadmap:        {path.relative_to(repo_root).as_posix()}")
            print()
        return 0

    if args.command == "next":
        path = resolve_workstream(repo_root, args.workstream)
        roadmap = load_roadmap(path)
        print(f"{roadmap['title']} ({roadmap['slug']}) - {roadmap['status']}")
        print(f"{progress_line(roadmap)}")
        print()
        current = tasks_by_status(roadmap, "IN_PROGRESS")
        if current:
            print("IN PROGRESS")
            for task in current:
                print(f"  {task['id']}  {task['title']}")
                print(f"    resume: {task.get('resume_note', '')}")
            print()
        ready = tasks_by_status(roadmap, "READY")
        print("READY" if ready else "READY: none")
        for task in ready:
            print(f"  {task['id']}  {task['title']}")
            print(f"    init: python3 scripts/content_workstream.py init {roadmap['slug']} --task {task['id']}")
        print()
        blocked = tasks_by_status(roadmap, "BLOCKED")
        if blocked:
            print("BLOCKED")
            for task in blocked:
                print(f"  {task['id']}  {task['title']}")
                for item in task.get("blockers", []):
                    print(f"    blocker: {item}")
                for item in task.get("open_decisions", []):
                    print(f"    open decision (user-owned): {item}")
            print()
        waiting = [t for t in roadmap["tasks"] if t["status"] == "PLANNED" and unmet_deps(roadmap, t)]
        if waiting:
            print("WAITING ON DEPENDENCIES")
            for task in waiting:
                unmet = ", ".join(f"{d} ({s})" for d, s in unmet_deps(roadmap, task))
                print(f"  {task['id']}  waiting on {unmet}")
        return 0

    if args.command == "init":
        path = resolve_workstream(repo_root, args.workstream)
        roadmap = load_roadmap(path)
        errors = validate(roadmap, repo_root, path)
        if errors:
            print(f"content_workstream: {path} does not validate; fix it before initializing", file=sys.stderr)
            for err in errors:
                print(f"  - {err}", file=sys.stderr)
            return 1
        task = find_task(roadmap, args.task)
        packet, ok = init_packet(roadmap, task, repo_root)
        stream = sys.stdout if ok else sys.stderr
        print("\n".join(packet), file=stream)
        return 0 if ok else 1

    parser.print_help()
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
